-- V1__Initial_Schema.sql
CREATE TABLE IF NOT EXISTS users (
  id bigint NOT NULL AUTO_INCREMENT,
  username varchar(50) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  email varchar(100) NOT NULL UNIQUE,
  full_name varchar(100) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  role enum('ROLE_ADMIN','ROLE_USER') NOT NULL,
  is_active bit(1) NOT NULL DEFAULT b'1',
  is_two_factor_enabled bit(1) NOT NULL DEFAULT b'0',
  two_factor_secret varchar(32) DEFAULT NULL,
  two_factor_method varchar(10) DEFAULT NULL,
  avatar_url varchar(255) DEFAULT NULL,
  token_version int NOT NULL DEFAULT 0,
  points bigint DEFAULT 0,
  membership_tier varchar(20) DEFAULT NULL,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  failed_login_attempts int DEFAULT 0,
  lock_until datetime(6) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categories (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL UNIQUE,
  description text,
  image_url varchar(255) DEFAULT NULL,
  is_active bit(1) NOT NULL DEFAULT b'1',
  created_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS farms (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(150) NOT NULL,
  owner_name varchar(100) DEFAULT NULL,
  province varchar(100) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  description text,
  image_url varchar(255) DEFAULT NULL,
  contact_phone varchar(20) DEFAULT NULL,
  contact_email varchar(100) DEFAULT NULL,
  certification enum('GLOBAL_GAP','HACCP','NONE','ORGANIC','VIETGAP') NOT NULL,
  certification_code varchar(100) DEFAULT NULL,
  certification_expiry_date date DEFAULT NULL,
  is_active bit(1) NOT NULL DEFAULT b'1',
  latitude double DEFAULT NULL,
  longitude double DEFAULT NULL,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(200) NOT NULL,
  description text,
  price decimal(15,2) NOT NULL,
  original_price decimal(15,2) DEFAULT NULL,
  unit varchar(50) DEFAULT NULL,
  image_url varchar(255) DEFAULT NULL,
  is_active bit(1) NOT NULL DEFAULT b'1',
  is_new bit(1) NOT NULL DEFAULT b'0',
  category_id bigint NOT NULL,
  farm_id bigint NOT NULL,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (category_id) REFERENCES categories (id),
  FOREIGN KEY (farm_id) REFERENCES farms (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS coupons (
  id bigint NOT NULL AUTO_INCREMENT,
  code varchar(50) NOT NULL UNIQUE,
  description varchar(255) DEFAULT NULL,
  discount_percent int NOT NULL,
  min_order_amount decimal(15,2) DEFAULT NULL,
  max_discount_amount decimal(15,2) DEFAULT NULL,
  expiry_date date NOT NULL,
  usage_limit int DEFAULT NULL,
  used_count int NOT NULL DEFAULT 0,
  is_active bit(1) NOT NULL DEFAULT b'1',
  is_private bit(1) NOT NULL DEFAULT b'0',
  created_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id bigint NOT NULL AUTO_INCREMENT,
  order_code varchar(30) NOT NULL UNIQUE,
  user_id bigint NOT NULL,
  shipping_address varchar(300) NOT NULL,
  address_detail varchar(300) DEFAULT NULL,
  ward varchar(100) DEFAULT NULL,
  district varchar(100) DEFAULT NULL,
  province varchar(100) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  receiver_name varchar(100) DEFAULT NULL,
  tracking_number varchar(50) DEFAULT NULL,
  estimated_arrival datetime(6) DEFAULT NULL,
  payment_method enum('BANK_TRANSFER','COD','MOMO','ONLINE','VNPAY') NOT NULL,
  status enum('PENDING','CONFIRMED','PACKAGING','SHIPPING','DELIVERED','CANCELLED','RETURN_REQUESTED','RETURNED','RETURN_REJECTED') NOT NULL,
  total_amount decimal(15,2) NOT NULL,
  discount_amount decimal(15,2) DEFAULT NULL,
  shipping_fee decimal(15,2) DEFAULT 0,
  final_amount decimal(15,2) NOT NULL,
  is_paid bit(1) NOT NULL DEFAULT b'0',
  is_refunded bit(1) NOT NULL DEFAULT b'0',
  refunded_at datetime(6) DEFAULT NULL,
  note varchar(500) DEFAULT NULL,
  return_reason varchar(500) DEFAULT NULL,
  return_media varchar(500) DEFAULT NULL,
  reject_reason varchar(500) DEFAULT NULL,
  coupon_id bigint DEFAULT NULL,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  confirmed_at datetime(6) DEFAULT NULL,
  packaging_at datetime(6) DEFAULT NULL,
  shipped_at datetime(6) DEFAULT NULL,
  delivered_at datetime(6) DEFAULT NULL,
  cancelled_at datetime(6) DEFAULT NULL,
  paid_at datetime(6) DEFAULT NULL,
  return_requested_at datetime(6) DEFAULT NULL,
  returned_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id),
  FOREIGN KEY (coupon_id) REFERENCES coupons (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
